# Generated by Django 4.1.7 on 2023-03-20 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusOfOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordstatus', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Статус',
            },
        ),
        migrations.CreateModel(
            name='WorkerJobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Должность',
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('secondname', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=30)),
                ('photo', models.URLField(default=None)),
                ('jobtitle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job', to='cafe.workerjobtitle')),
            ],
            options={
                'verbose_name': 'Работник',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordertype', models.CharField(max_length=50)),
                ('table', models.CharField(max_length=25)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(default=10, null=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Status', to='cafe.statusoforder')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Workers', to='cafe.workers')),
            ],
            options={
                'verbose_name': 'Заказы',
            },
        ),
    ]
