# Generated by Django 4.1.7 on 2023-03-21 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='ordertype',
        ),
    ]
